source 'https://rubygems.org'

gem 'rails', '~> 4.1.4'
gem 'pg', '~> 0.17.1'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'bcrypt-ruby', '~> 3.1.5'
gem 'angularjs-rails', '~> 1.2.19'
gem 'jquery-rails', '~> 3.1.1'
gem "devise"
gem 'annotate', '~> 2.6.5'
gem 'simple_form', '~> 3.0.2'
gem 'will_paginate', '~> 3.0.6'
gem 'bootstrap-will_paginate', '~> 0.0.10'
gem 'rails_best_practices', '~> 1.15.4'
gem 'reek', '~> 1.3.7'
gem 'sass-rails', '~> 4.0.3'
gem 'coffee-rails', '~> 4.0.1'
gem 'uglifier', '~> 2.5.1'
gem 'bootstrap-sass', '~> 3.2.0.0'
gem 'font-awesome-sass-rails', '~> 3.0.2.2'

group :development do
  gem 'better_errors', '~> 1.1.0'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'pry', '~> 0.10.0'
  gem 'pry-doc', '~> 0.6.0'
  gem 'brakeman', '~> 2.6.1', :require => false
  gem 'meta_request', '~> 0.3.0'
  gem 'spring'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0.1'
  gem 'capybara', '~> 2.3.0'
  gem 'launchy', '~> 2.4.2'
  gem 'factory_girl_rails', '~> 4.4.1'
end

gem 'sdoc', '~> 0.4.0', group: :doc